version: '2.1'

services:
    rt1:
        image: snisioi/cap2:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - cap2net
        ports:
         - "8001:8001"
         - "8001:8001/udp"
    rt2:
        image: snisioi/cap2:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - cap2net
networks:
    cap2net:
        ipam:
            driver: default
            config:
                - subnet: 172.9.0.0/16 
                  gateway: 172.9.1.1
