apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: laborator
type: Opaque
data:
  # echo -n "notes_password_123" | base64  →  bm90ZXNfcGFzc3dvcmRfMTIz
  POSTGRES_PASSWORD: bm90ZXNfcGFzc3dvcmRfMTIz
  # echo -n "notes_user" | base64          →  bm90ZXNfdXNlcg==
  POSTGRES_USER: bm90ZXNfdXNlcg==
