FROM snisioi/cap2

MAINTAINER Sergiu Nisioi <sergiu.nisioi@fmi.unibuc.ro>

USER root

RUN apt-get update && apt-get install -y iptables iproute2

RUN pip3 install --upgrade python-iptables


COPY src/*.sh /

