apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: seminar
type: Opaque
data:
  # Valorile din Secret trebuie să fie codificate în base64.
  # Comanda pentru a codifica: echo -n "valoarea-ta" | base64
  # Comanda pentru a decodifica: echo "dmFsb2FyZWEtdGE=" | base64 --decode
  #
  # "parola-redis-123" in base64:
  REDIS_PASSWORD: cGFyb2xhLXJlZGlzLTEyMw==
